# azure-pipelines.yml - configuration for Azure Pipelines
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
trigger:
  - master
  - release/**
  - feature/**
stages:
  - stage: Default
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        variables:
          - group: gpg
        steps:
          - task: DownloadSecureFile@1
            name: gpgKeys
            inputs:
              secureFile: keys.asc
          - bash: |
              echo '$(gpg.passphrase)' | \
              sh ./setupkeys.sh '$(gpgKeys.secureFilePath)'
            displayName: Set up signing keys
          - task: Cache@2
            inputs:
              key: maven | $(Agent.OS) | **/pom.xml
              path: $(Agent.BuildDirectory)/.m2/repository
              restoreKeys: |
                maven | $(Agent.OS)
                maven
          - task: Maven@3
            inputs:
              goals: package gpg:sign
              options: -B -P ossrh -Duser.home=$(Agent.BuildDirectory)
              jdkVersion: "1.8"
