# docker-compose.yml - compose file for test containers
# Copyright (C) 2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
version: "2.1"
services:
  texteditor:
    image: kazssym/wildfly:latest
    ports:
      - "${TEXTEDITOR_HTTP_PORT:-8080}:8080"
      - "${TEXTEDITOR_DEBUG_PORT:-8787}:8787"
    environment:
      DEBUG:
      DEBUG_PORT: 0.0.0.0:8787
      OPENJ9_JAVA_OPTIONS: -Xtune:virtualized -Xshareclasses
    volumes:
      - ./texteditor/target/texteditor-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war:ro
      - javasharedresources:/root/javasharedresources:rw
    working_dir: /opt/jboss/wildfly/standalone
    command: /opt/jboss/wildfly/bin/standalone.sh -b=0.0.0.0
    cap_drop:
      - ALL
  toybox:
    image: kazssym/wildfly:latest
    ports:
      - "${TOYBOX_HTTP_PORT:-8082}:8080"
      - "${TOYBOX_DEBUG_PORT:-8789}:8787"
    environment:
      DEBUG:
      DEBUG_PORT: 0.0.0.0:8787
      OPENJ9_JAVA_OPTIONS: -Xtune:virtualized -Xshareclasses
    volumes:
      - ./toybox/target/toybox-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war:ro
      - javasharedresources:/root/javasharedresources:rw
    working_dir: /opt/jboss/wildfly/standalone
    command: /opt/jboss/wildfly/bin/standalone.sh -b=0.0.0.0
    cap_drop:
      - ALL
volumes:
  javasharedresources: {}
